import asyncio
import base64
import logging
import os
import traceback
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import requests
from duckduckgo_search import DDGS
from livekit.agents import function_tool, RunContext

# Gmail OAuth
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# Global error registry
from error_log import log_error, get_recent_errors, clear_errors, format_errors_for_agent

logger = logging.getLogger("friday-tools")

SCOPES           = ["https://www.googleapis.com/auth/gmail.send"]
TOKEN_FILE       = os.path.join(os.path.dirname(__file__), "token.json")
CREDENTIALS_FILE = os.path.join(os.path.dirname(__file__), "credentials.json")

# ---------------------------------------------------------------------------
# Per-email diagnostics (last attempt only — for check_email_status)
# ---------------------------------------------------------------------------

_email_diagnostics: dict = {
    "last_status":    None,
    "last_recipient": None,
    "last_subject":   None,
    "last_error":     None,
    "last_error_detail": None,
    "auth_result":    None,
    "send_result":    None,
}


def _reset_email_diagnostics():
    for k in _email_diagnostics:
        _email_diagnostics[k] = None


# ---------------------------------------------------------------------------
# Gmail OAuth helper
# ---------------------------------------------------------------------------

def _get_gmail_service():
    """
    Load Gmail OAuth credentials.
    Works in two modes:
      1. Local:  reads token.json from disk (generated by gmail_auth.py)
      2. Cloud:  reads GMAIL_TOKEN_JSON environment variable (set in Railway/Render dashboard)
    """
    import json as _json

    token_json_env = os.getenv("GMAIL_TOKEN_JSON")

    if token_json_env:
        # ── Cloud mode: token loaded from environment variable ────────────
        logger.info("[EMAIL] Loading Gmail token from GMAIL_TOKEN_JSON env var.")
        creds = Credentials.from_authorized_user_info(
            _json.loads(token_json_env), SCOPES
        )
    elif os.path.exists(TOKEN_FILE):
        # ── Local mode: token loaded from token.json file ─────────────────
        logger.info("[EMAIL] Loading Gmail token from token.json file.")
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    else:
        raise FileNotFoundError(
            "Gmail token not found. Either:\n"
            "  Local:  run 'python gmail_auth.py' to generate token.json\n"
            "  Cloud:  set GMAIL_TOKEN_JSON env var in your hosting dashboard"
        )

    if not creds.valid:
        if creds.expired and creds.refresh_token:
            logger.info("[EMAIL] Refreshing expired OAuth token...")
            creds.refresh(Request())
            # Save back locally if running with a file
            if os.path.exists(TOKEN_FILE):
                with open(TOKEN_FILE, "w") as f:
                    f.write(creds.to_json())
                logger.info("[EMAIL] Token refreshed and saved to token.json.")
            else:
                logger.info("[EMAIL] Token refreshed (cloud mode — not saved to disk).")
        else:
            raise RuntimeError(
                "Gmail OAuth token is invalid and cannot be refreshed.\n"
                "  Local:  run 'python gmail_auth.py' again\n"
                "  Cloud:  update GMAIL_TOKEN_JSON env var with a fresh token"
            )

    return build("gmail", "v1", credentials=creds)



# ---------------------------------------------------------------------------
# Weather Tool
# ---------------------------------------------------------------------------

def _fetch_weather_sync(city: str) -> str:
    response = requests.get(f"https://wttr.in/{city}?format=4", timeout=10)
    if response.status_code == 200:
        return response.text.strip()
    return f"Could not retrieve weather for {city} (HTTP {response.status_code})."


@function_tool()
async def get_weather(
    context: RunContext,  # type: ignore
    city: str,
) -> str:
    """Get detailed current weather for a given city including temperature, condition, humidity and wind."""
    try:
        result = await asyncio.to_thread(_fetch_weather_sync, city)
        logger.info(f"[WEATHER] {city}: {result}")
        return result
    except requests.Timeout:
        err = f"Weather request timed out for '{city}'."
        logger.error(f"[WEATHER] {err}")
        log_error(
            source="get_weather",
            error=err,
            detail=traceback.format_exc(),
            suggestion="Check your internet connection. The wttr.in service may be slow — try again in a moment.",
        )
        return f"Sorry, the weather request timed out for {city}. Please try again."
    except Exception as e:
        err = f"Weather lookup failed for '{city}': {e}"
        logger.error(f"[WEATHER] {err}")
        log_error(
            source="get_weather",
            error=err,
            detail=traceback.format_exc(),
            suggestion="Verify the city name is correct. If the error persists, the weather service may be down.",
        )
        return f"An error occurred while retrieving weather for {city}."


# ---------------------------------------------------------------------------
# Web Search Tool
# ---------------------------------------------------------------------------

def _search_web_sync(query: str) -> str:
    """
    Direct DuckDuckGo search using DDGS API (no langchain wrapper).
    Retries up to 3 times with backoff — handles cloud IP rate-limiting.
    """
    import time
    last_error = None
    for attempt in range(1, 4):  # 3 attempts
        try:
            with DDGS() as ddgs:
                results = list(ddgs.text(query, max_results=5))
            if not results:
                return f"No search results found for '{query}'."
            # Format results clearly for the agent to read aloud
            formatted = []
            for i, r in enumerate(results, 1):
                title = r.get("title", "Result")
                body  = r.get("body", "")
                formatted.append(f"{i}. {title}\n   {body}")
            return "\n\n".join(formatted)
        except Exception as e:
            last_error = e
            logger.warning(f"[SEARCH] Attempt {attempt}/3 failed: {e}")
            if attempt < 3:
                time.sleep(2 * attempt)  # 2s, then 4s backoff
    raise last_error  # re-raise after all retries exhausted


@function_tool()
async def search_web(
    context: RunContext,  # type: ignore
    query: str,
) -> str:
    """Search the web using DuckDuckGo for general knowledge, news, or any topic."""
    try:
        results = await asyncio.to_thread(_search_web_sync, query)
        logger.info(f"[SEARCH] '{query}': {results[:200]}...")
        return results
    except Exception as e:
        err = f"Web search failed for '{query}': {e}"
        logger.error(f"[SEARCH] {err}")
        log_error(
            source="search_web",
            error=err,
            detail=traceback.format_exc(),
            suggestion=(
                "DuckDuckGo is rate-limiting this server's IP. "
                "This is common on cloud platforms. Try again in 30 seconds."
            ),
        )
        return f"Sorry, I was unable to search for '{query}' right now. DuckDuckGo may be temporarily blocking this server. Please try again in a moment."


# ---------------------------------------------------------------------------
# Email Tool  (Gmail REST API — HTTPS, no SMTP ports needed)
# ---------------------------------------------------------------------------

def _send_email_sync(
    recipient_list: list[str],
    subject: str,
    plain_message: str,
    cc_email: Optional[str] = None,
) -> str:
    _email_diagnostics["last_recipient"] = ", ".join(recipient_list)
    _email_diagnostics["last_subject"]   = subject
    _email_diagnostics["last_status"]    = "failed"

    # ── Auth ─────────────────────────────────────────────────────────────────
    try:
        service = _get_gmail_service()
        _email_diagnostics["auth_result"] = "success"
        logger.info("[EMAIL] Gmail OAuth OK.")
    except FileNotFoundError as e:
        _email_diagnostics["auth_result"] = f"FAILED: {e}"
        suggestion = (
            "Run 'python gmail_auth.py' in the project folder. "
            "A browser will open — sign in with your Gmail account. "
            "This only needs to be done once."
        )
        log_error("send_email", str(e), traceback.format_exc(), suggestion)
        logger.error(f"[EMAIL] Auth failed: {e}")
        _email_diagnostics["last_error"]        = str(e)
        _email_diagnostics["last_error_detail"] = suggestion
        return "Email failed: Not authenticated. Please run 'python gmail_auth.py' first."
    except Exception as e:
        _email_diagnostics["auth_result"] = f"FAILED: {e}"
        log_error("send_email", f"OAuth error: {e}", traceback.format_exc(),
                  "Run 'python gmail_auth.py' to re-authenticate.")
        logger.error(f"[EMAIL] OAuth error: {e}")
        _email_diagnostics["last_error"] = str(e)
        return f"Email failed: Authentication error — {e}"

    # ── Build message ─────────────────────────────────────────────────────────
    msg = MIMEMultipart("alternative")
    msg["From"]    = "me"
    msg["To"]      = ", ".join(recipient_list)
    msg["Subject"] = subject
    all_recipients = recipient_list.copy()
    if cc_email:
        msg["Cc"] = cc_email
        all_recipients.append(cc_email)

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; font-size: 15px; color: #222; line-height: 1.6;">
        <div style="max-width: 640px; margin: 0 auto; padding: 24px;">
          {plain_message.replace(chr(10), '<br>')}
        </div>
      </body>
    </html>
    """
    msg.attach(MIMEText(plain_message, "plain", "utf-8"))
    msg.attach(MIMEText(html_body,    "html",  "utf-8"))

    # ── Send ──────────────────────────────────────────────────────────────────
    try:
        raw    = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        result = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        _email_diagnostics["send_result"] = f"success (id: {result.get('id')})"
        _email_diagnostics["last_status"] = "success"
        _email_diagnostics["last_error"]  = None
        logger.info(f"[EMAIL] ✓ Sent to {all_recipients}. ID: {result.get('id')}")
        return f"Email successfully sent to {', '.join(recipient_list)}."

    except HttpError as api_err:
        code   = api_err.resp.status
        detail = str(api_err)
        hint   = _api_error_hint(code)
        _email_diagnostics["send_result"] = f"HTTP {code}"
        _email_diagnostics["last_error"]  = f"Gmail API error {code}"
        log_error(
            "send_email",
            f"Gmail API HTTP {code}: {detail}",
            traceback.format_exc(),
            hint,
        )
        logger.error(f"[EMAIL] API error {code}: {detail}")
        return f"Email failed: Gmail API error {code}. Say 'check email error' for diagnosis."

    except Exception as e:
        log_error("send_email", f"Send failed: {e}", traceback.format_exc(),
                  "Check your Gmail quota and internet connection.")
        logger.error(f"[EMAIL] Send failed: {e}")
        _email_diagnostics["last_error"] = str(e)
        return f"Email failed: {e}"


def _api_error_hint(status_code: int) -> str:
    return {
        400: "Bad request — the email address or message format may be invalid.",
        401: "Unauthorized — token.json may be expired. Run 'python gmail_auth.py' again.",
        403: "Forbidden — Gmail API may not be enabled in Google Cloud Console, or the OAuth scope is wrong.",
        429: "Rate limit hit — you've sent too many emails in a short period. Wait and retry.",
        500: "Google server error — try again in a few seconds.",
    }.get(status_code, "Check the Google Cloud Console error logs for more detail.")


@function_tool()
async def send_email(
    context: RunContext,  # type: ignore
    to_emails: str,
    subject: str,
    message: str,
    cc_email: Optional[str] = None,
) -> str:
    """
    Send an email using Gmail (via HTTPS — works on all networks).

    Args:
        to_emails: Recipient email address(es). Single or comma-separated.
        subject:   Email subject line.
        message:   Email body text.
        cc_email:  Optional CC address.
    """
    _reset_email_diagnostics()
    try:
        recipient_list = [e.strip() for e in to_emails.split(",")]
        logger.info(f"[EMAIL] → To: {recipient_list} | Subject: '{subject}'")
        result = await asyncio.to_thread(
            _send_email_sync, recipient_list, subject, message, cc_email
        )
        logger.info(f"[EMAIL] Tool result: {result}")
        return result
    except Exception as e:
        detail = traceback.format_exc()
        log_error("send_email", f"Critical tool error: {e}", detail,
                  "Restart the agent. If it persists, check error_log.py.")
        logger.error(f"[EMAIL] Critical: {e}\n{detail}")
        return f"A critical error occurred while sending the email: {e}"


# ---------------------------------------------------------------------------
# Email Diagnostics Tool
# ---------------------------------------------------------------------------

@function_tool()
async def check_email_status(
    context: RunContext,  # type: ignore
) -> str:
    """
    Return the full diagnosis of the last email attempt.
    Call this when the user asks why their email failed or says 'check email error'.
    """
    d = _email_diagnostics
    if d["last_status"] is None:
        return "No email has been attempted yet in this session."
    if d["last_status"] == "success":
        return (
            f"Last email sent successfully via Gmail API.\n"
            f"  To: {d['last_recipient']}\n"
            f"  Subject: {d['last_subject']}\n"
            f"  Result: {d['send_result']}"
        )
    lines = [
        "━━━ EMAIL FAILURE DIAGNOSIS ━━━",
        f"Recipient  : {d['last_recipient'] or 'unknown'}",
        f"Subject    : {d['last_subject'] or 'unknown'}",
        "",
        f"Auth (OAuth)  : {d['auth_result'] or 'not attempted'}",
        f"Send (API)    : {d['send_result'] or 'not attempted'}",
        "",
        f"Error: {d['last_error'] or 'none'}",
        "",
        d["last_error_detail"] or "No detail available.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# System Error Log Tool
# ---------------------------------------------------------------------------

@function_tool()
async def check_system_errors(
    context: RunContext,  # type: ignore
) -> str:
    """
    Return all errors logged by any tool during this session.
    Call this when the user asks things like:
      - 'what errors happened?'
      - 'show me the error log'
      - 'what went wrong?'
      - 'any problems so far?'
    After reporting the errors, always summarise them in plain English
    and offer actionable suggestions to fix each one.
    """
    errors = get_recent_errors(20)
    report = format_errors_for_agent(errors)
    logger.info(f"[ERRLOG] Diagnostics requested — {len(errors)} error(s) found.")
    return report


@function_tool()
async def clear_error_log(
    context: RunContext,  # type: ignore
) -> str:
    """
    Clear the system error log.
    Call this when the user says 'clear errors', 'reset the log', or 'forget the errors'.
    """
    count = len(get_recent_errors(100))
    clear_errors()
    logger.info("[ERRLOG] Error log cleared by user request.")
    return f"Done, sir. {count} error(s) have been cleared from the system log."